### ISSUE TITLE
Does HC plan to use AWS Lambda's new Telemetry API?

### ISSUE THREAD

**Issue by mcblair** [honeycombio/honeycomb-lambda-extension#124]
Performance with ADOT Layer is far from ideal, New Relic and Datadog have already built an extension for the new Telemetry API. Does Honeycomb have plans?

References:
- https://aws.amazon.com/blogs/compute/introducing-the-aws-lambda-telemetry-api/
- https://github.com/aws-samples/aws-lambda-extensions/tree/main/go-example-telemetry-api-extension

**Comment by cartermp** [comment]
Heya, so far we don't have an immediate plan to use the Lambda Telemetry API. We did know about this early on and participated in some super early-access sessions, but because it didn't have a way to emit OTLP directly we ultimately passed on this, as it would represent a third way to get data out of lambda.

AWS does plan to rectify both the OpenTelemetry problem and the issue of this not quite obviating the exist Logs API that this extension uses. But for now we felt that we'd be spreading ourselves too thin by maintaining three different ways to get data in from Lamda.

As an alternative to the heavier weight ADOT layer, have you considered sending data directly from lamda like so? https://opentelemetry.io/docs/instrumentation/js/serverless/#aws-lambda
