### ISSUE TITLE
reduce size of binary in lambda layer

### ISSUE THREAD

**Issue by ryansb** [honeycombio/honeycomb-lambda-extension#18]
The deployed layers (from account 702835727665) are ~3MB larger than strictly necessary. The binaries are being uploaded before being stripped, which leaves debug and other symbols in the binary and can impact Lambda startup times. 

More importantly, for functions near the Lambda zip/total size limit this can push over and make the function update fail. 

From Ubuntu, you can add to the build steps in the readme: 

```bash
apt-get update
apt-get install -y binutils
strip extensions/*
```

This reduces the on-disk size of the extension from 8MB to 5.1MB without impacting perf/features. If there's a reason not to strip the binary, no worries and please close this issue out.

**Comment by robbkidd** [comment]
Seems worth consideration! Thank you for catching that, @ryansb.

I think there's another option to achieve the same result with [linker flags](https://golang.org/cmd/link/) for the build, too: `go build -ldflags "-s -w" ...`

```
» ls -sk bin/extensions
total 14144
 5860 honeycomb-lambda-extension
 8284 honeycomb-lambda-extension-debug
```

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
