### ISSUE TITLE
Add lambda extension version into event `data`

### ISSUE THREAD

**Issue by dstrelau** [honeycombio/honeycomb-lambda-extension#68]
It would be nice to be able to report on the version of the lambda extension that's being used, similar to the way that [the beeline injects `meta.beeline_version` into each event](https://github.com/honeycombio/beeline-go/blob/main/beeline.go#L158). Ideally, we'd get both `GOARCH` and `version`?

**Comment by JamieDanielson** [comment]
Looks like this was added in #112 ([see this line here](https://github.com/honeycombio/honeycomb-lambda-extension/pull/112/files#diff-f8cc8fac931e6e2673c1efd189bf9364306e2053415bc12c6e9b5324b3dccbebR53)):

`UserAgentAddition: fmt.Sprintf("honeycomb-lambda-extension/%s (%s)", version, runtime.GOARCH),`

Combined with the changes we made to the name (using revision in name instead of relying on layer number), this is how it shows up in Honeycomb:

![lambda-extension-version-with-arch](https://user-images.githubusercontent.com/29520003/221674397-ccf28c3c-be24-4e13-92ee-15d27633e2ea.png)
